###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [24]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]  -- List
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [25]:
get_state(4)

[[ 9 15  3  5]
 [10  7  0 14]
 [ 4  2 12  8]
 [ 6 11  1 13]]


[9, 15, 3, 5, 10, 7, 0, 14, 4, 2, 12, 8, 6, 11, 1, 13]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [26]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    #print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)): 
               if state[i] > state[j]: 
                             if state[j] != 0 : 
                               count = count + 1 
                    
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [27]:
s = get_state(4)
count_inversion(s)

[[ 6 15  9  2]
 [11  7  1 12]
 [ 0  4  5  3]
 [14 10 13  8]]


49

# **Find blank row**

In [45]:
# find row position of the blank tile
import math
def get_blank_row(state):
  count=0
  N = math.sqrt(len(state))
  for i in range(len(state)):
    if(state[i]==0):
      count=i+1
      break
  return (N+1-math.ceil(count/N))
          


In [46]:
get_blank_row(s)

2.0

In [44]:
count_inversion(s)

49

In [39]:
print(s)

[6, 15, 9, 2, 11, 7, 1, 12, 0, 4, 5, 3, 14, 10, 13, 8]


# Solvability Rules

In [58]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
 # N = ?
 # I = ?#call function here
 # R = ?#call function here
  # decide solvability
   I = count_inversion(initialState)
   N = math.sqrt(len(initialState))
   R = get_blank_row(initialState)
  
   if (N%2==1 and I%2==0):
        return True
   elif(N%2==0 and R%2==1 and I%2==0):
        return True
   elif(N%2==0 and R%2==0 and I%2==1):
        return True
   else:
      return False
  


In [59]:
S = get_state(4)
isSolvable(S)


[[ 1  6  7  3]
 [13  2  5  8]
 [ 4 12 14  9]
 [10 15  0 11]]


True

In [53]:
get_blank_row(s)

2.0